version: '2'
services:
  workflow:
    build: .
    volumes:
      - "/home/ghjnut/projects/ci:/usr/src/app"
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - jenkins
  jenkins:
    image: jenkins
    ports:
      - "8080"
      - "50000"
