version: '2'
services:
  workflow:
    build: .
    volumes:
      - "/home/ghjnut/projects/ci:/usr/src/app"
    depends_on:
      - jenkins
  jenkins:
    image: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
